#!/bin/bash
# This script sets up your agent once you login

_SSH_AGENT_PID_FILE=${HOME}/.agent.pid
_SSH_AGENT_SOCK_FILE=${HOME}/.agent.sock

function _ssh_new_agent(){
	# Otherwise set it up
	echo Setting up new SSH Agent
	eval `ssh-agent`
	echo ${SSH_AGENT_PID} > ${_SSH_AGENT_PID_FILE}
	echo ${SSH_AUTH_SOCK} > ${_SSH_AGENT_SOCK_FILE}
	ssh-add
}

function ssh_reconnect_agent(){
	# ex
	# SSH_AGENT_PID=19738
	# SSH_AUTH_SOCK=/tmp/ssh-QPVgQ19737/agent.19737
	if [ -f ${_SSH_AGENT_PID_FILE} -a -f ${_SSH_AGENT_SOCK_FILE} ]; then
		PID=`cat ${_SSH_AGENT_PID_FILE}`
		SOCK=`cat ${_SSH_AGENT_SOCK_FILE}`
		ps -fp ${PID} 2>/dev/null >/dev/null
		if [ $? -eq 0 ];then
			export SSH_AGENT_PID=${PID}
			export SSH_AUTH_SOCK=${SOCK}
		else
			_ssh_new_agent
		fi
	else
		_ssh_new_agent
	fi
}
